### Exercises

**Our test function:**

```
function foo (shouldFail){
  return function (errCb, successCb) {
    shouldFail ? errCb(new Error('What were the chances?')) : successCb(true)
  }
}

addLog(foo(true))(failure, success)
```

**Some helpers**
```
function success (successful) {
  console.log("It was a success! We got", successful)
}

function failure (error) {
  console.log("It all went wrong! We got", error)
}
```

```
function addLog (eitherErrorOrSuccess) {
  return function (errCb, successCb) {

    function myNewErrCb (err) {
      Log(err)
      errCb(err)
    }

    return eitherErrorOrSuccess(myNewErrCb, successCb)
  }
}
```

```
function capitaliseErrorMessage (eitherErrorOrSuccess) {
  return function (errCb, successCb) {

    function myNewErrCb (err) {
      errCb(new Error(err.message.toUpperCase()))
    }

    return eitherErrorOrSuccess(myNewErrCb, successCb)
  }
}
```

**Test**: `addLog(capitaliseErrorMessage(foo(true)))(failure, success)`

```
function logSuccessfulValue (eitherErrorOrSuccess) {
  return function (errCb, successCb) {

    function myNewSuccessCb (data) {
      Log(data)
      successCb(data)
    }

    return eitherErrorOrSuccess(errCb, myNewSuccessCb)
  }
}
```
**Test**: `logSuccessfulValue(foo(false))(failure, success)`

```
function try2PossibleMistakes (eitherErrorOrSuccess, somethingThatMightFail) {
  return function (failureCb, successCb) {
    function newSuccessCb (data) {
      somethingThatMightFail(data)(failureCb, successCb)
    }

    eitherErrorOrSuccess(failureCb, newSuccessCb)
  }
}
```

**Test**:
```
try2PossibleMistakes(foo(true), foo)(failure, success)
try2PossibleMistakes(foo(false), foo)(failure, success)
```


```
function Log (x) {
  console.log("Hello everyone!", x)
}
```
